config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  get 'teas' => "teas#index"
  get 'teas/lookup' => "teas#lookup"
  get 'teas/missing' => "teas#missing"
  get 'teas/:id' => "teas#show", as: :tea

end

app/models/tea.rb
class Tea < ActiveRecord::Base
  def self.lookup(lookup)
    teas = where(name: lookup)
    if teas.empty?
      return nil
    end
    return teas[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController
  def index
    @teas = Tea.all
  end
  def show
    @tea = Tea.find(params[:id])
  end
  def lookup
    @tea = Tea.lookup(params[:lookup])
    if @tea != nil
      redirect_to tea_path(@tea.id)
    else
      redirect_to teas_missing_path
    end
  end
  def missing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tea Harmony</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/main.html.erb
<p>Tea Harmony<p>
<p><%= link_to "Teas", teas_path %></p>
<%= form_tag(teas_lookup_path, method: "get") do %>
  <%= label_tag(:lookup, "Search for:") %>
  <%= text_field_tag(:lookup) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/teas/index.html.erb
<h1>All Teas</h1>
<% @teas.each do |tea| %>
  <p><%= tea.name %><p>
  <p><%= tea.serving %><p>
  <p><%= tea.category %><p>
  <p><%= tea.origin %><p>
  <p><%= tea.caffeine %><p>
  <p><%= tea.description %><p>
  <img src=<%= tea.image %>>
<% end %>

app/views/teas/lookup.html.erb
<% if @tea.present? %>
  <h1><%= @tea.name %></h1>
  <p><%= @tea.serving %><p>
  <p><%= @tea.category %><p>
  <p><%= @tea.origin %><p>
  <p><%= @tea.caffeine %><p>
  <p><%= @tea.description %><p>
  <img src=<%= @tea.image %>>
<% else %>
  <p>Tea with this name is unavailable<p>
<%end%>

app/views/teas/missing.html.erb
<p>Sorry! We couldn't find the tea you were looking for<p>

app/views/teas/show.html.erb
<h1><%= @tea.name %></h1>
<p><%= @tea.serving %><p>
<p><%= @tea.category %><p>
<p><%= @tea.origin %><p>
<p><%= @tea.caffeine %><p>
<p><%= @tea.description %><p>
<img src=<%= @tea.image %>>